In [2]:
#A DataFrame is a 2-dimensional data structure that can store data of different types (including characters,
#  integers, floating point values, categorical data and more) in columns. 

import pandas as pd

In [3]:
a = pd.DataFrame(
    {
        "name": [
            "Haris",
            "Ahmad"
        ],
        "age": [18, 21]
    }
)
a

    name  age
0  Haris   18
1  Ahmad   21

In [23]:
a.describe()

            age
count   2.00000
mean   19.50000
std     2.12132
min    18.00000
25%    18.75000
50%    19.50000
75%    20.25000
max    21.00000

In [18]:
print(a["age"])
a["age"].max()

0    18
1    21
Name: age, dtype: int64

np.int64(21)

In [ ]:
age = pd.Series([1,2,3],name = "Age")
print(age)

0    1
1    2
2    3
Name: Age, dtype: int64

In [19]:
df = pd.DataFrame(
    {
        "sno":[1,2,3,4,5]
    }
)
df["sno"].max()

np.int64(5)

In [ ]:
df.describe()